### ISSUE TITLE
Add more docker image tags

### ISSUE THREAD

**Issue by anescobar1991** [americanexpress/one-app#100]
# 💡 Feature request

For each of the docker images that are released for One App it would be great to see a `latest` tag so that a user can if they choose always develop against the latest version of One App.

Similarly each major version of One App should have a tag where the latest semver compatible version for that major is also published. For example `oneamex/one-app:5` would always point to the latest 5.x.x release.

**Comment by nellyk** [comment]
Reopening as we would need to add the tags for all the sem versions 
 example process releasing 5.1.0: 
```
$ docker build -t oneamex/one-app:latest .
$ docker push oneamex/one-app:latest
$ docker tag oneamex/one-app:latest oneamex/one-app:5
$ docker push oneamex/one-app:5
$ docker tag oneamex/one-app:latest oneamex/one-app:5.1
$ docker push oneamex/one-app:5.1
$ docker tag oneamex/one-app:latest oneamex/one-app:5.1.0
$ docker push registry:5.1.0
```
