### ISSUE TITLE
Adding Dependabot to whitelist for CLA assistant

### ISSUE THREAD

**Issue by shivaylamba** [americanexpress/one-app#134]
# 💡 Feature request

Some of the PRs created by Dependabot were not merged since the Dependabot cant sign the CLA Agreement. But using this help link : https://github.com/cla-assistant/cla-assistant#can-i-whitelist-bot-users we can whitelist the CLA Assistant so that it doesnt stop it when it creates a PR. 

## Is your feature request related to a problem? Please describe

Some of the PRs created by Dependabot were not merged since the Dependabot cant sign the CLA Agreement. But using this help link : https://github.com/cla-assistant/cla-assistant#can-i-whitelist-bot-users we can whitelist the CLA Assistant so that it doesnt stop it when it creates a PR. 
A clear and concise description of what you want and what your use case is.

## Example
[americanexpress/one-app] chore(deps): bump acorn from 6.4.0 to 6.4.1 in /prod-sample/sample-modules/frank-the-parrot/0.0.0 (#93

## Describe the solution you'd like

Whitelisting the dependabot for CLA Assistant agreement.

**Comment by shivaylamba** [comment]
@nellyk Could you look into this

**Comment by nellyk** [comment]
Thanks for raising this, we are looking at whitelisting the bot

**Comment by JamesSingleton** [comment]
@nellyk and @shivaylamba this has now been completed.
