### ISSUE TITLE
Bump up Github Actions for Stale to "version": "2.0.0"

### ISSUE THREAD

**Issue by shivaylamba** [americanexpress/one-app#150]
# 💡 Feature request
Request to bump the version of Stale github action from @v1 to @v2. 

## Is your feature request related to a problem? Please describe
Just an update to the github action.

**Comment by JamesSingleton** [comment]
@shivaylamba this PR takes care of this and actually bumps it to `v3` https://github.com/americanexpress/one-app/pull/153

**Comment by shivaylamba** [comment]
Okay sir!

**Comment by JamesSingleton** [comment]
@shivaylamba these has been merged in
