### ISSUE TITLE
`loadModuleData` is not being called client-side. 

### ISSUE THREAD

**Issue by infoxicator** [americanexpress/one-app#57]
# 🐞 Bug Report

## Describe the bug

The docs mention that `The loadModuleData Module Lifecycle Hook, is executed on the Server and Browser when a Module is loaded in either environment.` However it is not being called client-side when navigating using `<Link />` from one-app-router.

## To Reproduce

This can be reproduced in the `healthy-frank` prod sample module

1. Go to 'http://localhost:3000/healthy-frank/simple'
2. Click on 'baby frank'
4. The default state ```{ "isLoading": false, "isComplete": false, "data": null, "error": null }``` is displayed

## Expected behavior

When navigating using `<Link />`, `loadModuleData` should run client-side, fetch the data and perform the updates to the redux store.

## System information

- OS:  [macOS]
- Browser (if applies) [chrome, safari]
- Version of one-app: [e.g. 5.0.0]
- Node version:[e.g 12.14.1]
- Are you using building one-app from source or using the release Docker image? Source

**Comment by infoxicator** [comment]
I can see that this behaviour is deliberate by looking at the integration tests https://github.com/americanexpress/one-app/blob/master/__tests__/integration/one-app.spec.js#L802 however I would like to know the reasoning behind it, and secondly what's the best way to fetch data in both the client and the server when not using Iguazu.

**Comment by mtomcal** [comment]
I have noticed this occurs in the Module Root but it calls `loadModuleData` in the client for a Child Module when using `ModuleRoute`.

**Comment by infoxicator** [comment]
I have also managed to reproduce making the call from a child module, and the way the `healthy-frank` and `ssr-frank` modules are structured, the call is made from the child module not the root. Let me know if can be of help debugging the issue 👍
