### ISSUE TITLE
Create Recipe for Making API Calls

### ISSUE THREAD

**Issue by JamesSingleton** [americanexpress/one-app#59]
Create a recipe on how to make API calls within One App. This documentation should be added here: https://github.com/americanexpress/one-app/blob/master/docs/recipes/Making-An-API-Call.md

*Topics that should be Covered*

* How to make calls using the [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)
* How to make calls using [Iguazu](https://github.com/americanexpress/iguazu)

**Comment by infoxicator** [comment]
I am willing to take this one 👍, however need clarification about this issue first https://github.com/americanexpress/one-app/issues/57

**Comment by infoxicator** [comment]
added here https://github.com/americanexpress/one-app/pull/387
