### ISSUE TITLE
Create Recipe for enabling Server Side Rendering

### ISSUE THREAD

**Issue by JamesSingleton** [americanexpress/one-app#61]
Create a recipe on how to enable Server Side Rendering. This documentation should be added here: https://github.com/americanexpress/one-app/blob/master/docs/recipes/Enabling-Serverside-Rendering.md

*Topics that should be Covered*

* How to enable without Iguazu
* How to enable with Iguazu/ iguazu-holocron

**Comment by giulianok** [comment]
@JamesSingleton I'm currently investigating this, can you point to the files that will allow me to accomplish that?

**Comment by JamesSingleton** [comment]
@giulianok, this is a GitHub issue to create that documentation.

**Comment by giulianok** [comment]
@JamesSingleton isn't this issue related to the Recipe (example of how to use it) not the Documentation?

**Comment by JamesSingleton** [comment]
The recipe would basically be a how to.

**Comment by johnlister** [comment]
@JamesSingleton I'd be interested in the SSR recipe(s) as well or any other information you can provide. Do you have an ETA for completing the documentation? Currently evaluating microfrontend frameworks and one-app seems a good fit for us.

**Comment by infoxicator** [comment]
This has been added by @JamesSingleton here https://github.com/americanexpress/one-app/commit/ddb88c58ca70e4f11e4dc5b93f795089fe5e7824
