### ISSUE TITLE
Multiple errors displaying in browser console

### ISSUE THREAD

**Issue by rohantarai** [americanexpress/one-app#74]
# 🐞 Bug Report

## Describe the bug

my module was running and i opened http://localhost:3000 and it worked but then i opened chrome dev tools and i found errors in console.

## To Reproduce

it can be reproduced by:
1. creating a new module
2. serving it with one-app
3. running one-app
4. visiting http://localhost:3000 
5. opening chrome dev tools then console tab

## Expected behavior

multiple errors are being displayed in browser console.

## Screenshots

![chrome console errors](https://user-images.githubusercontent.com/16543074/76885136-ca872080-68a4-11ea-8b6b-0224d931c30c.PNG)

## System information

- OS: Windows
- Browser (if applies): chrome v80
- Version of one-app: 5.0.0
- Node version: 12.16.1
- Are you using building one-app from source or using the release Docker image? -from source
- Hosting platform for one-app server: localhost
- Hosting platform/CDN for your one-app modules: localhost

## Additional context

NA

**Comment by JamesSingleton** [comment]
@rohantarai,

That first error you are getting is due to the font url not being added to the CSP. https://github.com/americanexpress/one-app/blob/master/docs/api/modules/App-Configuration.md#csp goes over how to create a CSP.

**Comment by rohantarai** [comment]
Ok i solved two issues which were caused due to chrome extensions. now i left with other two issues related to reactjs. i hope this will be fixed in upcoming version.

![Capture](https://user-images.githubusercontent.com/16543074/77469320-e22a5000-6e34-11ea-80f9-edadcb048c5d.PNG)

**Comment by JamesSingleton** [comment]
@rohantarai,

This is due to [`@americanexpress/one-app-router`](https://github.com/americanexpress/one-app-router) using those lifecycle methods and `one-app` running in strict mode.
