### ISSUE TITLE
getHtmlAttributesString does not reflect htmlAttributes in SSR

### ISSUE THREAD

**Issue by eddhurst** [americanexpress/one-app#954]
# 🐞 Bug Report

## Describe the bug

When providing htmlAttributes prop to react-helmet, they are not being reflected in the server render of the html element.

## To Reproduce

If my root component is configured thus:

```jsx
<Helmet
  htmlAttributes={{
    lang: locale,
  }}
/>
  {children}
</Helmet>
```

## Expected behavior

I would expect to see the lang attribute reflected on the server render of the page. If we were to log the documentElement on the initial client side render however, there are no attributes reflected.

It looks like the [getHtmlAttributesString](https://github.com/americanexpress/one-app/blob/9b0c4b3d5a1a8830225e4bf62d18f8ba566c5a07/src/server/plugins/reactHtml/index.jsx#L154) function would allow for this, but seemingly not

```js
console.info(globalThis.document.documentElement.outerHTML);
```

## Screenshots

<img width="531" alt="Screenshot 2023-03-17 at 17 26 59" src="https://user-images.githubusercontent.com/9933592/225979971-618f7273-b593-4880-8754-9430d6936bc4.png">

## System information

- OS: Mac
- Browser (if applies): Edge
- Version of one-app: 6
- Node version: 16
- Are you using building one-app from source or using the release Docker image? docker image

**Comment by 10xLaCroixDrinker** [comment]
Does this only have to do with the `lang` attribute or others as well? `lang` should be set when dispatching `updateLocale()`. If you are doing both, you'll likely get some inconsistencies.
